### ISSUE TITLE
Duration wrong when setting start/end time individually

### ISSUE THREAD

**Issue by Alexamakans** [dinkur/dinkur#57]
Running `dinkur@latest` on `Ubuntu 22.04`.

Sometimes the duration reported will be 1 second less than the actual duration.

Tested:
- Setting just start time, bug occurs.
- Setting just end time, bug occurs.
- Setting both at the same time, bug does not occur.

Note:
- The duration goes from 1:29:59 -> 1:30:00 -> 1:29:59, seemingly at random.
- It says `No changes were applied` when setting to the same end time as it currently is, but not when setting the start time, possibly related?

![dinkur](https://user-images.githubusercontent.com/79503481/170233031-6eb03fbd-32f9-41d9-b3e1-19faa95aaef3.png)

**Comment by jilleJr** [comment]
"No changes applied" is missing a newline as well 🤔

This is highly probably related to my time code. I think I'm doing a +1 second somewhere. I'll have to double-check.

Thanks for the elaborate bug report 😄

**Comment by jilleJr** [comment]
Found the culprit: It seems to be using the current nanosecond timestamp when parsing the time.

This seems to be a bug from <https://github.com/olebedev/when>.

**Comment by jilleJr** [comment]
Bug has been fixed. To try out the new version you can run:

```sh
go install -tags='fts5' -ldflags='-s -w' github.com/dinkur/dinkur@90e73ccf66e937afad28e827b9dcd6a194015ba9
```

(Using `@latest` will used your locally cached version for a while, instead of the actual latest version)
